{% set name = "apischema" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wyfo/apischema/archive/v{{ version }}.tar.gz
  sha256: c0beb17bdb1ce846bc060a68ef2e88556ea4366872f11a9590e81cc5c36c3cf1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    # dataclasses is only required for Python 3.6.  conda is smart enough to
    # not install it for Python >=3.7 in this noarch build.  See the
    # conda-forge knowledgebase on empty Python packages.
    - dataclasses
  run_constrained:
    # The following is needed for the (optional) apischema.graphql to work properly:
    - graphql-core >=3.0.0

test:
  imports:
    - apischema

about:
  home: https://github.com/wyfo/apischema
  doc_url: https://wyfo.github.io/apischema
  dev_url: https://github.com/wyfo/apischema
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: JSON (de)serialization, GraphQL and JSON schema generation using Python typing.

extra:
  recipe-maintainers:
    - klauer
    - wyfo
