{% set name = "apischema" %}
{% set version = "0.18.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wyfo/apischema/archive/v{{ version }}.tar.gz
  sha256: ba08a064e7707807b21ee21aade5c7b81e63b8132368b6bc7fc9426a479f20be

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
  run_constrained:
    # The following is needed for the (optional) apischema.graphql to work properly:
    - graphql-core >=3.0.0

test:
  imports:
    - apischema

about:
  home: https://github.com/wyfo/apischema
  doc_url: https://wyfo.github.io/apischema
  dev_url: https://github.com/wyfo/apischema
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: JSON (de)serialization, GraphQL and JSON schema generation using Python typing.

extra:
  recipe-maintainers:
    - klauer
    - wyfo
